### ISSUE TITLE
stopAnimation not working

### ISSUE THREAD

**Issue by digabriel** [leandroBorgesFerreira/LoadingButtonAndroid#1]
When i call `stopAnimation()` (without calling `revertAnimation()`) the animation does not stop and the loading progress continues running.

Here's my code:

```
 followButton.startAnimation();
 final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        // Do something after 5s = 5000ms
                        followButton.stopAnimation();
                        followButton.setText("\u2713");
                        followButton.setTextSize(18);
                    }
                }, 5000);
```

**Comment by leandroBorgesFerreira** [comment]
Hey Gabriel,

I will take a look and fix the problem tonight. 

For now, I can say that "followButton.stopAnimation();" is supposed to only freeze the animation. If you want to display a text in the button, you will have to call "followButton.revertAnimation();" so the button will go back to be a normal button (not a loading spinner)

**Comment by digabriel** [comment]
Hi Leandro, thanks for your quick reply.

I try to call revertAnimation() and then set a new text, but after the revert animations ends, the button text go back to the original text, not the new one that i set. Example

```
               // Here the button original text is "Follow"
                followButton.startAnimation();
                
                final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        followButton.revertAnimation();
                        followButton.setText("\u2713");
                        followButton.setTextSize(18);
                        // After i set the new text the button still presenting "Follow" when revert animation ends
                    }
                }, 2000);
```

**Comment by leandroBorgesFerreira** [comment]
I just ran your code. The animation didn't stopped, you are right. I will fix and then i will tell you when its ready.

You are trying to make a "Done" status, right? I will add a "removeAnimation" so it will work as you expect. Then will work on a more polished version of a 'Done' status, the button doesn't support that right now.

**Comment by leandroBorgesFerreira** [comment]
@digabriel I fixed the problem, the lib will work as you expect now. Use the version `compile 'br.com.simplepass:loading-button-android:1.3.0'`. 

I also added the method 
`doneLoagingAnimation(int fillColor, Bitmap doneImage);` 
I does a Done status in a polished way, you can choose the color and the image of the status.

**Comment by digabriel** [comment]
Thanks you very much @leandroBorgesFerreira!!!

**Comment by leandroBorgesFerreira** [comment]
You are welcome!
