### ISSUE TITLE
Add integration test in Travis-CI

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [leandroBorgesFerreira/LoadingButtonAndroid#101]
The PR #89 have integration tests. This library needs the integration tests to run on Travis-CI to make sure that the integration tests added keep corrected as more code is added here.

**Comment by leandroBorgesFerreira** [comment]
Seggested by: @wokkaflokka

**Comment by wokkaflokka** [comment]
Resolved by https://github.com/cavega/LoadingButtonAndroid/pull/1
