### ISSUE TITLE
Suggestion: Use Androidx Lifecycle to Internalize Disposal of Retained Memory

### ISSUE THREAD

**Issue by wokkaflokka** [leandroBorgesFerreira/LoadingButtonAndroid#102]
README currently mentions the requirement of calling dispose in `onDestroy` to avoid leaking memory. This library might be able to make use of the `androidx` lifecycle components in a way where memory management can be internalized by the library, rather than pushed to consumers.

**Comment by leandroBorgesFerreira** [comment]
@wokkaflokka I don't have much experience with the new Androidx Lifecycle. Could you open a PR showing how this could be done or give further explanations?

**Comment by wokkaflokka** [comment]
👍 will do.
