### ISSUE TITLE
documentation - Explain about Andoidx support

### ISSUE THREAD

**Issue by venkat8995** [leandroBorgesFerreira/LoadingButtonAndroid#105]
- [ ] Manifest merger failed 

: Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:14:5-58:19 to override.

**Comment by leandroBorgesFerreira** [comment]
Hello @venkat8995. Could you paste the code of your `build.gradle`? 

It seams that you're trying to use the version 2.0.+ of this library with the android support library. Prior to the 2.0.0 version, this button only accepts androidx. If you need to use this button with android support library, use the 1.14.0 version.

**Comment by davidHarush** [comment]
> It seams that you're trying to use the version 2.0.+ of this library with the android support library. Prior to the 2.0.0 version, this button only accepts androidx. If you need to use this button with android support library, use the 1.14.0 version.

I think it would be a good idea to write it down in the `README.md`

**Comment by mul1sh** [comment]
> > It seams that you're trying to use the version 2.0.+ of this library with the android support library. Prior to the 2.0.0 version, this button only accepts androidx. If you need to use this button with android support library, use the 1.14.0 version.
> 
> I think it would be a good idea to write it down in the `README.md`

@leandroBorgesFerreira I think this is necessary because i also ran into the same issue

Nonetheless thanks for the great work in this lib 🙂

**Comment by leandroBorgesFerreira** [comment]
Done
