### ISSUE TITLE
Pre commit hook for lint

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [leandroBorgesFerreira/LoadingButtonAndroid#109]
It would be good to have a pre commit hook for running lint before commiting to the repo. Although this is not mandatory, it can make the life of contributors a lot easier.

**Comment by leandroBorgesFerreira** [comment]
@cavega

**Comment by cavega** [comment]
@leandroBorgesFerreira PR submitted :)

**Comment by leandroBorgesFerreira** [comment]
Merged
