### ISSUE TITLE
Button with shadow like cardview

### ISSUE THREAD

**Issue by Kishanjvaghela** [leandroBorgesFerreira/LoadingButtonAndroid#11]
I want to use the button with shadow same like material CardView. I this possible with this library? or any alternative solution?

**Comment by leandroBorgesFerreira** [comment]
Hello Kishanjvaghela. The animation will happen only in the button, not in the CardView. But you can accomplish what you are looking for with this button. All you have to do is to use a drawable in the background for rounded corners and set the elevation of you button to create a shadow. If you are targeting a version before 21, you can set the shadow in the drawable.
