### ISSUE TITLE
Callback in onAnimationEnd() for startAnimation()

### ISSUE THREAD

**Issue by NicolasDucom** [leandroBorgesFerreira/LoadingButtonAndroid#117]
Hi !
When I click on the button and send a network call, I'd like to be able to wait for the button to finish animating using a callback like for the revertAnimation() call before sending my request,  would that be possible ? 
Thank you !

**Comment by leandroBorgesFerreira** [comment]
Hi @NicolasDucom the Button doesn't have support for this yet, but it is very to do. Why don't you open a PR for this? Shouldn't take long

**Comment by NicolasDucom** [comment]
Sure ! No problem 👍

**Comment by leandroBorgesFerreira** [comment]
I am on a trip right now. I will release a new version as soon as I am back. Just a few days.

**Comment by leandroBorgesFerreira** [comment]
This is fixed, right?
