### ISSUE TITLE
Cannot change image when calling doneLoadingAnimation() a second time

### ISSUE THREAD

**Issue by cdongieux** [leandroBorgesFerreira/LoadingButtonAndroid#120]
Hi,

I'm using your button to launch an action that might succeed or fail.
When it succeeds, I call `doneLoadingAnimation(colorSuccess, bitmapSuccess)`, and when it fails I call `doneLoadingAnimation(colorFailure, bitmapFailure)`.
The first time I click the button, if the action fails the animation displays as expected. But after that if the action succeeds, the animation does *not* displays as expected.

Best regards.

**Comment by leandroBorgesFerreira** [comment]
@cdongieux I will take a look at this behaviour. Unfortunately I am taking care of some personal matters, so it may take some time =/

**Comment by MuriloCalegari** [comment]
Any known workarounds?

**Comment by leandroBorgesFerreira** [comment]
This should be fixed in the 2.1.1 version
