### ISSUE TITLE
loadingButton.revertAnimation() NullpointerException

### ISSUE THREAD

**Issue by vincenzoaceto** [leandroBorgesFerreira/LoadingButtonAndroid#13]
Hi, i found a issue in your library when i use .revertAnimation() method.
If i use twice the method on a button, nullpointerException occurred. Why?

the message:
"Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                                 at br.com.simplepass.loading_button_lib.customViews.CircularProgressButton.revertAnimation(CircularProgressButton.java:279)"

**Comment by leandroBorgesFerreira** [comment]
Hi Vicenzoaceto, I just tested with two revertAnimation being called, but I didn't get any NullPointerException. Could share the code that presented this error, so I can reproduce it?

**Comment by leandroBorgesFerreira** [comment]
Vicenzo, there was an exception when calling revertAnimation before startAnimation where I got a NullPointerException. Was this your problem? I was solved in the 1.7.1 version

**Comment by vincenzoaceto** [comment]
hi leandro, that's my problem! Thanks to your answer and to your fix. I'm going to update the library. Thank you very much.

**Comment by leandroBorgesFerreira** [comment]
You are welcome! Thanks for your contribution!
