### ISSUE TITLE
startAnimation(); is not working with no parameters?

### ISSUE THREAD

**Issue by Angelbreath** [leandroBorgesFerreira/LoadingButtonAndroid#151]
if (clickedButton.getText().equals( Common.questionList.get(index).getCorrectAnswer())) {
                //Chose correct answer
                clickedButton.startAnimation();

Cannot resolve startAnimation(); It asks for bitmap and fill color. Is that correct?

**Comment by leandroBorgesFerreira** [comment]
Now you can use `startAnimation()` in Java with no problem. Please use the `2.2.0` version

**Comment by rishabhvjv** [comment]
startAnimation() not working with library version 1.14.0, can't use latest version as am using AppCompat in my project
