### ISSUE TITLE
startAnimation() asks for Function0<Unit> onAnimationEndListener

### ISSUE THREAD

**Issue by MrMak21** [leandroBorgesFerreira/LoadingButtonAndroid#152]
the same asks the revertAnimation(). What i am suppose to put there?

**Comment by leandroBorgesFerreira** [comment]
Now you can use `revertAnimation()` in Java prior to the version 2.2.0. Please check the new version

**Comment by MrMak21** [comment]
ok thank you very much for the fast response!!
