### ISSUE TITLE
Keep the button in middle of the screen when animating 

### ISSUE THREAD

**Issue by HWSTS** [leandroBorgesFerreira/LoadingButtonAndroid#158]
Hi,

Is there a way to keep the button in the middle of the screen after animation start ? its going to the screen left side

**Comment by samair** [comment]
Even i have the same problem..

**Comment by HWSTS** [comment]
@samair I think its because of the frame layout that i use, check layout gravity its should work i will update once get solution

**Comment by HWSTS** [comment]
No, still not working even when change the layout and set the layout gravity to center!

**Comment by samair** [comment]
Yep, found solution, put it in a relativelayout and make the buton "layout_CenterInParent " to true and then it works.. let me know.

**Comment by leandroBorgesFerreira** [comment]
Sorry that I took so long to answer that question. The button animation will respected the gravity of the ViewGroup it is inserted, so put it inside a LinearLayout with centre gravity would be the best idea for this view. Also, you can use relativelayout, like @samair suggested.

**Comment by leandroBorgesFerreira** [comment]
I'm closing this bug since there's no correction to be done, just fix the gravity of the ViewGroup that contains this button and everything should be fine.
