### ISSUE TITLE
How to make the button return to it's previous state?

### ISSUE THREAD

**Issue by karanthakakr04** [leandroBorgesFerreira/LoadingButtonAndroid#16]
I have successfully implemented this library in my dem app **but now what I want is the button to go back to it's state before pressing it**. Similar to what is displayed on the main page of this library. This is my code so far:

```
circularProgressButton = (CircularProgressButton) findViewById(R.id.sign_in_button);

        circularProgressButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                AsyncTask<String, String, String> signInActivity = new AsyncTask<String, String, String>() {
                    @Override
                    protected String doInBackground(String... params) {
                        try{
                            Thread.sleep(3000);
                        } catch (InterruptedException e){
                            e.printStackTrace();
                        }
                        return "done";
                    }

                    @Override
                    protected void onPostExecute(String s) {
                        if(s.equals("done")){
                                circularProgressButton.doneLoadingAnimation(Color.parseColor("#FF4081"), BitmapFactory.decodeResource(getResources(), R.drawable.ic_done_white_48dp));
                                Toast.makeText(MainActivity.this, "Welcome!", Toast.LENGTH_SHORT).show();
                        }
                    }
                };
                circularProgressButton.startAnimation();
                signInActivity.execute();
            }
        });
```
I am trying to implement this for my login functionality. I want the button to go back to it's initial state but I can't understand how is it possible here?
Any help here would be appreciated!

**Comment by leandroBorgesFerreira** [comment]
You can use circularProgressButton.revertAnimation()

**Comment by leandroBorgesFerreira** [comment]
Hello @karanthakakr04. Did the revertAnimation worked for you?

**Comment by karanthakakr04** [comment]
@leandroBorgesFerreira I didn't try it yet. Once I do, I'll post an update here. Thanks for replying.

**Comment by karanthakakr04** [comment]
@leandroBorgesFerreira Revert animation is not working for me. Could your please do us a favor and upload a sample repo explaining how to use this repository with appropriate comments?

**Comment by leandroBorgesFerreira** [comment]
Could your try this code? I believe it does what you need

        final CircularProgressButton circularProgressButton = (CircularProgressButton) 
        findViewById(R.id.sign_in_button);

        circularProgressButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                AsyncTask<String, String, String> signInActivity = new AsyncTask<String, String, String>() {
                    @Override
                    protected String doInBackground(String... params) {
                        try{
                            Thread.sleep(3000);
                        } catch (InterruptedException e){
                            e.printStackTrace();
                        }
                        return "done";
                    }

                    @Override
                    protected void onPostExecute(String s) {
                        if(s.equals("done")){
                            circularProgressButton.doneLoadingAnimation(Color.parseColor("#FF4081"), BitmapFactory.decodeResource(getResources(), R.drawable.ic_done_white_48dp));

                            Runnable runnable = new Runnable() {
                                @Override
                                public void run() {
                                    circularProgressButton.revertAnimation();
                                }
                            };
                            
                            new Handler().postDelayed(runnable, 1000);

                            Toast.makeText(MainActivity.this, "Welcome!", Toast.LENGTH_SHORT).show();
                        }
                    }
                };
                circularProgressButton.startAnimation();
                signInActivity.execute();

**Comment by karanthakakr04** [comment]
Thanks @leandroBorgesFerreira I'll surely try it and get back to you.
