### ISSUE TITLE
[Bug] Reverting removes the rounded corners

### ISSUE THREAD

**Issue by CarlosEsco** [leandroBorgesFerreira/LoadingButtonAndroid#163]
If the button is reverted the rounded edges of the button are removed.  It's repeatable in the included app on the repo

**Comment by CarlosEsco** [comment]
actually if you set the initial corner angle it works, i do think however if you are using a style and it sets the corners either the app needs to ignore the style complete so you have to set the intial corner no matter what, or it reads the styles initial corners

**Comment by basusingh** [comment]
I had the same issue. I used a drawable to set rounded corner and background colours and used the initial and final radius.

[https://github.com/leandroBorgesFerreira/LoadingButtonAndroid/issues/164](url)
