### ISSUE TITLE
Cannot set default background color

### ISSUE THREAD

**Issue by HosseinArabbeigi** [leandroBorgesFerreira/LoadingButtonAndroid#174]
I need to set default  background color, but button loses the corner angles:

```Koltin
<br.com.simplepass.loadingbutton.customViews.CircularProgressButton
        android:id="@+id/home_connect_bt"
        android:layout_width="@dimen/_50sdp"
        android:layout_height="@dimen/_50sdp"
        android:textSize="18sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="@id/home_title_tv"
        android:background="@color/red_1"/>
```

**Comment by Dave181295** [comment]
Got the same issue

**Comment by leandroBorgesFerreira** [comment]
Hello hello. Did you set the desired corner angle? I don't see it in your XML

**Comment by HosseinArabbeigi** [comment]
Thanks @leandroBorgesFerreira  for your response, sorry in above code I forgot to add corners radius but I had the problem and finally implemented the view without using library.

**Comment by leandroBorgesFerreira** [comment]
Oh ok. Good to see that this is no longer a problem. I'll close it then.
