### ISSUE TITLE
Animation don't have AnimationPlayEndCallback????

### ISSUE THREAD

**Issue by liangjingkanji** [leandroBorgesFerreira/LoadingButtonAndroid#19]

**Comment by leandroBorgesFerreira** [comment]
Hello @liangjingkanji, could you explain better what are your needs and maybe the use case?

**Comment by liangjingkanji** [comment]
my think 

![](https://ws3.sinaimg.cn/large/006tNc79gy1fikqfvts69j316q0tct9z.jpg)

**Comment by leandroBorgesFerreira** [comment]
@liangjingkanji The button can perform the flowchart with no problems. All you have to do is to use the:

- circularButton.startAnimation()
- circularButton.doneLoadingAnimation(fillColor, bitmap)
- circularButton.revertAnimation()

You need to use those methods in the right moment. If you share what you tried so far I can give you a little help
