### ISSUE TITLE
Alterar Texto do Botão

### ISSUE THREAD

**Issue by felipeaugusto1** [leandroBorgesFerreira/LoadingButtonAndroid#2]
Como faz pra mudar o texto do botão após uma animação? Após um revertAnimation() eu não consigo alterar o texto do botão.

**Comment by leandroBorgesFerreira** [comment]
Oi Felipe, 

Acabei de adicionar um listener para quando a animação acabar. Basta fazer desse jeito:

circularProgressButton.revertAnimation(() -> circularProgressButton.setText("Animation reverted"));

ou:

circularProgressButton.revertAnimation(new OnAnimationEndListener() {
                @Override
                public void onAnimationEnd() {
                    circularProgressButton.setText("Seu texto aqui!");
                }
            });
