### ISSUE TITLE
button drawable getting cleared after animation

### ISSUE THREAD

**Issue by shahimclt** [leandroBorgesFerreira/LoadingButtonAndroid#21]
Drawables in buttons like `android:drawableLeft` are disappearing after `revertAnimation()` is called.

**Comment by Arcires** [comment]
@enzolupia 
Likewise, I have the same issue as you do. However, as per [this Issue](https://github.com/leandroBorgesFerreira/LoadingButtonAndroid/issues/30), it seems defining `initialCornerAngle="20dp"` solves this issue. It's not the ideal solution, but on a tight schedule, it does the job.
