### ISSUE TITLE
Not working in ContraintLayout with left and right contraints

### ISSUE THREAD

**Issue by michielkalle** [leandroBorgesFerreira/LoadingButtonAndroid#26]
`<br.com.simplepass.loading_button_lib.customViews.CircularProgressButton
            android:id="@+id/submit_settings"
            android:layout_width="0dp"
            android:layout_height="48dp"
            android:layout_margin="dimen/activity_layout_margin"
            android:background="drawable/button_submit"
            android:onClick="onClick"
            android:text="string/api_settings_submit"
            android:textColor="color/colorWhite"

            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/secret_layout"

            android:scaleType="fitCenter"
            android:src="drawable/ic_checkmark"
            app:spinning_bar_padding="0dp"
            app:spinning_bar_color="@color/colorBlack"
            app:spinning_bar_width="3dp"
            app:initialCornerAngle="0dp"
            app:finalCornerAngle="0dp" />

    </android.support.constraint.ConstraintLayout>`

`            saveButton.doneLoadingAnimation(
                    ContextCompat.getColor(getApplicationContext(), R.color.colorBlack),
                    BitmapFactory.decodeResource(getResources(), R.drawable.ic_checkmark));`

When the contraints are set on left and right, after calling the doneLoadingAnimation. the image/bitmap is stretched out.

**Comment by michielkalle** [comment]
When i remove the Left and Right contraints, its works okay, but then my button is not centred anymore,

**Comment by leandroBorgesFerreira** [comment]
The animation of this button does not center by defaukt. You need to set the gravity. Try to put it inside a linear layout in put gravity to center

**Comment by michielkalle** [comment]
Okey thanks! Then i will refactor my code.
