### ISSUE TITLE
revertAnimation() removes rounded corner

### ISSUE THREAD

**Issue by MuBoori** [leandroBorgesFerreira/LoadingButtonAndroid#30]
I have button with rounded corner. However, when I call revert revertAnimation the button become sharp with no rounded corner but it is  preserve the styling

**Comment by Lexycon** [comment]
Had same issue, "fixed" this by adding app:initialCornerAngle="10dp" in the xml... It seems to forget the styling... :-(

**Comment by MuBoori** [comment]
@Lexycon Thanks, It works.

**Comment by leandroBorgesFerreira** [comment]
Thanks for answering the question @Lexycon. Unfortunately there's not way to avoid the initialCornerAngle since there's no method to get the current corner angle from the background of the button. If someone knows a good solution for this, please let me know!

**Comment by indiefr** [comment]
@Lexycon Works! Thks!!!!!
