### ISSUE TITLE
Change background color in use

### ISSUE THREAD

**Issue by theo744** [leandroBorgesFerreira/LoadingButtonAndroid#33]
Hi,
When I change background color of the CircularProgressButton in use, the button doesn't get round during animation.
Here is my xml:
`<br.com.simplepass.loading_button_lib.customViews.CircularProgressButton
android:id="@+id/valider_date_livraison"
android:layout_width="match_parent"
android:layout_height="40dp"
android:layout_alignParentBottom="true"
android:layout_centerHorizontal="true"
android:background="@color/bleu"
android:text="SUIVANT"
android:textColor="@color/blanc"
android:textSize="16dp"
app:font="Gotham-Bold.otf"
app:spinning_bar_width="3dp"
app:spinning_bar_color="@color/blanc"
app:spinning_bar_padding="6dp"
app:initialCornerAngle="0dp">
</br.com.simplepass.loading_button_lib.customViews.CircularProgressButton>`

And here is the change of background color in the code:
`valider_date_livraison.setBackgroundColor(Color.GREEN);`

see the result on animation start:
![screenshot_20171215-014547](https://user-images.githubusercontent.com/23457995/34021405-f6c77c98-e139-11e7-981e-12598bff6c29.png)

Thanks for your help,
Théo

**Comment by leandroBorgesFerreira** [comment]
Are you setting the background color before the animation or during the animation?

**Comment by Dramtar** [comment]
hello, i have same trouble. in my case i need change background with animation when run 
`revertAnimation().` I'm studied the project code, and on my mind simple way to resolve this trouble, add some thing like 
`    public void setGradientDrawable(GradientDrawable gradientDrawable) {
        mGradientDrawable = gradientDrawable;
    }`

or `public void revertAnimation(final OnAnimationEndListener onAnimationEndListener, GradientDrawable gradientDrawable)) {
mGradientDrawable = gradientDrawable;

// here other code
}`

@leandroBorgesFerreira did you can do this? or say please how dynamical change background? Thanks)

**Comment by theo744** [comment]
I'm setting it before the animation and the background is always set back to the original color before animation start

**Comment by leandroBorgesFerreira** [comment]
You are right. It always come back to the original color. Will fix that.

**Comment by theo744** [comment]
Thanks, but the real problem here is that when you changed the background once in the java code, the button is'nt round anymore when animating

**Comment by leandroBorgesFerreira** [comment]
That's because this button doesn't override the setBackGroundColor of Button. So it changes the background of this button and this changes it's behaviour.

**Comment by leandroBorgesFerreira** [comment]
Hello @theo744. Try to use version 1.9.0 now. I am pretty sure it solves your problem. Happy coding!

**Comment by leandroBorgesFerreira** [comment]
Hi Dramtar. I still didn't test your use case, but I believe it was fixed in the 1.9.0 version. I will test this next week

**Comment by theo744** [comment]
Problem solved ! Thanks for your work and for your reactivity.
Best

**Comment by Dramtar** [comment]
Hi @leandroBorgesFerreira, yes, that's right, I just updated my library version and prefaced it to my case, everything works fine, thank you very much for the excellent library and your work)

**Comment by leandroBorgesFerreira** [comment]
You guys are welcome. Thanks for spotting  these bugs

**Comment by jahongir9779** [comment]
Hi, is this issue fixed? bcoz I'm still having the same problem on version 2.0.7. When I use setBackgroundColor() the button looses round corners
