### ISSUE TITLE
Manifest merge cause by min sdk version

### ISSUE THREAD

**Issue by riadhnet** [leandroBorgesFerreira/LoadingButtonAndroid#37]
Hello, 
Why min sdk version is 17 ?  i couldn't add to my project that have min sdk 16 

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [br.com.simplepass:loading-button-android:1.8.1] C:\Users\hptn\.gradle\caches\transforms-1\files-1.1\loading-button-android-1.11.1.aar\09162386e44c5299c9cec1c77f0f0787\AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 17,
  		or use tools:overrideLibrary="br.com.simplepass.loading_button_lib" to force usage (may lead to runtime failures)

any solution ? 
thanks

**Comment by leandroBorgesFerreira** [comment]
Hello @riadhnet. I this minSdkVersion is important to give support for compound drawable. This method: view.getCompoundDrawablesRelative is only available in the version.

If you don't need this feature, you can fork this project and compile using minSdk 16, just be aware to don't use compound drawables.

**Comment by leandroBorgesFerreira** [comment]
The minSdkVersion of this library is 16 now prior to the 2.0.0 version. There was a way to keep the compound drawables and use minSdk 16, after all.
