### ISSUE TITLE
Custom fonts not displayed

### ISSUE THREAD

**Issue by troncomputers** [leandroBorgesFerreira/LoadingButtonAndroid#47]
Hi!
I need help with custom fonts. On Preview (in Android Studio) works fine but when I build and launch on emulator it's not.
![loading_button_preview](https://user-images.githubusercontent.com/29543667/35852934-80e9f650-0b2c-11e8-9c16-58a9f1bdbeb4.png)

**Comment by leandroBorgesFerreira** [comment]
Hi @troncomputers. I just tested in my computer and the custom fonts works just fine. Witch version of this library are you using?

**Comment by troncomputers** [comment]
br.com.simplepass:loading-button-android:1.7.2

**Comment by leandroBorgesFerreira** [comment]
Update to 1.12.1 and you will be fine
