### ISSUE TITLE
Button is not going to the center

### ISSUE THREAD

**Issue by daniel0x7CC** [leandroBorgesFerreira/LoadingButtonAndroid#50]
I've already tried almost everything... but the progress keeps starting at the start position of the button and not in the center as it should..

(você é br, então... quando clico no botão, ao invés do progress ir pro meio da tela, ele fica no começo!!!)

**Comment by leandroBorgesFerreira** [comment]
Use the Button inside a Viewgroup with gravity at the center. This button respects the gravity of parent view group.

**Comment by daniel0x7CC** [comment]
it worked! thank you :)

**Comment by leandroBorgesFerreira** [comment]
Good to know it works now.

É nois
