### ISSUE TITLE
Merger Manifest Failed

### ISSUE THREAD

**Issue by searchy2** [leandroBorgesFerreira/LoadingButtonAndroid#6]
Unable to use library in project due to manifest merger failure. Perhaps increasing the Build Tools version to 25.0.2 will fix the problem?

**Comment by searchy2** [comment]
The issue could also be that his library is built off of Kotlin?

**Comment by leandroBorgesFerreira** [comment]
The fact that this library is not built for Kotlin should not be a problem. Kotlin is interoperable with Java. 

It is a bit hard to say what's wrong with your project and the library. Could you provide some stack trace or explain a little bit better the problem?

**Comment by searchy2** [comment]
I think it might just be the Build Tools. Will hold off and see.

**Comment by leandroBorgesFerreira** [comment]
Now the version 1.6.6 has the 25.0.2 build tools

**Comment by searchy2** [comment]
Thanks for the quick turnaround! The problem still persists and I suspect that Kotlin may be causing the issue. I have had issues with Kotlin libraries before :( 
Hopefully this is specific to my project. Closing issue as isolated incident.

**Comment by searchy2** [comment]
Oh shucks, I just realized that the Manifest merger failed because the minimum SDK version is 16 instead of 15.

**Comment by leandroBorgesFerreira** [comment]
I see... I will increase the compatility

**Comment by searchy2** [comment]
It's my fault for not noticing that is the problem,, sorry for the trouble :P
