### ISSUE TITLE
Fetch Location Using LoadingButtonAndroid

### ISSUE THREAD

**Issue by rajgar114** [leandroBorgesFerreira/LoadingButtonAndroid#60]
hey, I want to use this loading button as a progress dialog.
Means I want when user clicks it then i should fetch lat long and user should not interact with the activity and when the lat long are successfully fetched then the loading of this button should stop. How i can do that ?
Mainly i want the functionality of progress dialog with this loading button.

If i use asyn task still the user can interact with the activity...

**Comment by leandroBorgesFerreira** [comment]
I am closing this issue since it is not related to the library.
