### ISSUE TITLE
Use .png as background

### ISSUE THREAD

**Issue by tinkooladik** [leandroBorgesFerreira/LoadingButtonAndroid#64]
Is it possible to use .png or VectorDrawable as button background?
When I try to do so, it looks like this: 
![bcb3bf31-7b48-4f89-86fb-f294a4db5de7](https://user-images.githubusercontent.com/13711706/40726338-33656756-642e-11e8-8779-8e8df0b55adf.jpg)

even though corner angle was specified:
```
        circular:finalCornerAngle="50dp"
        circular:initialCornerAngle="0dp" // also tried "50dp"
```

Can I make it round circular after calling `.startAnimation();` and then return back to rectangular shape after `.revertAnimation();` ?

BTW done state also looks strange:
![94f1db19-7f84-4b89-9ae0-b6d2d78a5c97](https://user-images.githubusercontent.com/13711706/40727003-9c6c6078-642f-11e8-8f08-b6f4d90f2fd7.jpg)

**Comment by leandroBorgesFerreira** [comment]
Yes, sorry. You can't. This button only accepts solid colors

**Comment by leandroBorgesFerreira** [comment]
It is not possible to improve this library to accept `.png` because the only drawable that works with the morphing animation if the `GradientDrawable`. 

Since this problem can't be fixed, I am closing the issue. Please fell free to reopen it if you think there's a way to fix it.
