### ISSUE TITLE
how to centre rotating button after click

### ISSUE THREAD

**Issue by ARAlmac** [leandroBorgesFerreira/LoadingButtonAndroid#65]
I have it working although when I use circularprogressbar.startAnimation() the button loses its gravity and goes to the far left of the screen. 

How can I keep it centred?

**Comment by leandroBorgesFerreira** [comment]
Hello @ARAlmac. This button will respect the gravity of its parent ViewGroup. All you have to do is to use it inside a LinearLayout with center gravity and you're done.
