### ISSUE TITLE
onRevert back button drawable removed and cannot be applied

### ISSUE THREAD

**Issue by gurpreetjhajj23** [leandroBorgesFerreira/LoadingButtonAndroid#69]

**Comment by knight-shade** [comment]
Facing the same problem.
Initially the button has round corners, but after calling revert animation, it turns into rectangle button.

**Comment by traifdevelopment** [comment]
The same here.... What is the solution?

**Comment by nvpnair** [comment]
any solution?

**Comment by bilalhussainn** [comment]
Solution please.

**Comment by axionnneeeel** [comment]
Use app:initialCornerAngle attribute with the "dp" of the background button.

**Comment by traifdevelopment** [comment]
It works! Thank u axionnneeeel

**Comment by leandroBorgesFerreira** [comment]
I am glad it worked. Sorry I didn't respond this issue, I was super busy these last days.
