### ISSUE TITLE
Copy - Crash when calling doneLoagingAnimation before start animation ends

### ISSUE THREAD

**Issue by AlexandrPuryshev** [leandroBorgesFerreira/LoadingButtonAndroid#73]
Issue is still here. 
[Issue](https://github.com/leandroBorgesFerreira/LoadingButtonAndroid/issues/3)
https://github.com/leandroBorgesFerreira/LoadingButtonAndroid/issues/3#issuecomment-388874137

Often issue on android 8.0

**Comment by leandroBorgesFerreira** [comment]
This problem was corrected prior version 2.0.0. Just tested with a stop and done animation being called before the start animation ends and no problem happens. Fell free to reopen the issue if you still experience this bug.
