### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by davidHarush** [leandroBorgesFerreira/LoadingButtonAndroid#85]
Hey you can lower minSdkVersion to 16 ?
It will help me a lot.
Thanks...

**Comment by leandroBorgesFerreira** [comment]
Sorry David, some parts of the code need the minSdkVersion to be 19 =|. But you can clone this repository and remove then, it wouldn't be hard

**Comment by davidHarush** [comment]
Ok, thanks.

**Comment by leandroBorgesFerreira** [comment]
Actually, the minSdkVersion got changed to 16, turns out that it was possible.
