### ISSUE TITLE
use androidx libraries instead of appcompat

### ISSUE THREAD

**Issue by regogo** [leandroBorgesFerreira/LoadingButtonAndroid#90]
recently migrated to androidx libraries, im getting dependency errors from appcompat.

**Comment by leandroBorgesFerreira** [comment]
PR #89 solves this issue

**Comment by leandroBorgesFerreira** [comment]
PR #91 also solves this

**Comment by leandroBorgesFerreira** [comment]
This problem got solved in the 2.0.0 version of this library. Please try this new version.
